#!/usr/bin/env bash

# Ensure script is run with sudo
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this script with sudo (e.g., sudo ./rtsp-manager.sh)"
  exit 1
fi

REAL_USER=${SUDO_USER:-$(whoami)}
MEDIAMTX_BIN="/usr/local/bin/mediamtx"
CONFIG_FILE="/usr/local/etc/mediamtx.yml"
SERVER_SERVICE="/etc/systemd/system/mediamtx.service"
# We define the old publisher service path just so we can delete it if it exists
OLD_PUBLISH_SERVICE="/etc/systemd/system/rtsp-publisher.service"

echo "=========================================="
echo "    Raspberry Pi RTSP Stream Manager      "
echo "           (Single Service Mode)          "
echo "=========================================="

install_dependencies() {
    echo "[*] Checking dependencies..."
    apt-get update -qq
    apt-get install -y -qq ffmpeg wget tar curl iproute2

    if [ ! -f "$MEDIAMTX_BIN" ]; then
        echo "[*] Installing mediamtx..."
        VERSION="v1.9.1"
        ARCH=$(uname -m)
        if [ "$ARCH" == "aarch64" ]; then
            DL_ARCH="arm64"
        elif [[ "$ARCH" == armv7* ]]; then
            DL_ARCH="armv7"
        else
            echo "Unsupported architecture: $ARCH"
            exit 1
        fi
        
        curl -sL "https://github.com/bluenviron/mediamtx/releases/download/${VERSION}/mediamtx_${VERSION}_linux_${DL_ARCH}.tar.gz" | tar -xz -C /usr/local/bin mediamtx
        chmod +x "$MEDIAMTX_BIN"
        echo "[+] mediamtx installed."
    fi
}

setup_stream() {
    # 1. Clean up the old messy publisher service if it exists
    if [ -f "$OLD_PUBLISH_SERVICE" ]; then
        echo "[*] Cleaning up old publisher service..."
        systemctl disable --now rtsp-publisher.service 2>/dev/null
        rm -f "$OLD_PUBLISH_SERVICE"
    fi

    # 2. Get Video Path
    while true; do
        read -e -p "Enter the absolute path to your video file (.mp4): " VIDEO_PATH
        if [ -f "$VIDEO_PATH" ]; then
            break
        else
            echo "Error: File not found. Please provide a valid path."
        fi
    done

    # 3. Get Stream Name
    read -p "Enter the stream endpoint name (default: live): " STREAM_NAME
    STREAM_NAME=${STREAM_NAME:-live}

    # 4. Check for Port 8888 Conflicts
    DEFAULT_HLS=8888
    if ss -tulpn | grep -q ":8888 "; then
        echo "[!] Warning: Port 8888 is already in use (likely pigpiod)."
        DEFAULT_HLS=8899
    fi
    
    read -p "Enter HLS Port [$DEFAULT_HLS]: " HLS_PORT
    HLS_PORT=${HLS_PORT:-$DEFAULT_HLS}

    # 5. Generate the unified MediaMTX configuration file
    echo "[*] Generating MediaMTX configuration file..."
    mkdir -p /usr/local/etc
    cat <<EOF > "$CONFIG_FILE"
# Auto-generated by rtsp-manager.sh
hlsAddress: :$HLS_PORT

paths:
  $STREAM_NAME:
    runOnInit: /usr/bin/ffmpeg -re -stream_loop -1 -i "$VIDEO_PATH" -c copy -f rtsp rtsp://127.0.0.1:8554/$STREAM_NAME
    runOnInitRestart: yes
EOF

    # 6. Create MediaMTX Service
    echo "[*] Generating MediaMTX SystemD service..."
    cat <<EOF > "$SERVER_SERVICE"
[Unit]
Description=MediaMTX RTSP Server
After=network.target

[Service]
User=$REAL_USER
ExecStart=$MEDIAMTX_BIN
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

    # 7. Enable and Start
    echo "[*] Reloading SystemD and starting MediaMTX..."
    systemctl daemon-reload
    systemctl enable --now mediamtx.service

    PI_IP=$(hostname -I | awk '{print $1}')
    echo "=========================================="
    echo "[+] Setup Complete! Rock solid configuration deployed."
    echo "[+] RTSP Stream : rtsp://$PI_IP:8554/$STREAM_NAME"
    echo "[+] HLS Preview : http://$PI_IP:$HLS_PORT/$STREAM_NAME"
    echo "=========================================="
}

stop_stream() {
    echo "[*] Stopping and disabling MediaMTX..."
    systemctl disable --now mediamtx.service 2>/dev/null
    rm -f "$SERVER_SERVICE" "$CONFIG_FILE"
    systemctl daemon-reload
    echo "[+] Stream services and configuration removed."
}

# --- Main Menu ---
echo "1) Setup and Start RTSP Stream"
echo "2) Stop and Remove RTSP Stream"
echo "3) Check Status"
echo "4) Exit"
read -p "Choose an option [1-4]: " OPTION

case $OPTION in
    1)
        install_dependencies
        setup_stream
        ;;
    2)
        stop_stream
        ;;
    3)
        systemctl status mediamtx.service --no-pager
        ;;
    4)
        exit 0
        ;;
    *)
        echo "Invalid option."
        ;;
esac
